### ISSUE TITLE
ADPwdSpray2的recv_rep_tcp

### ISSUE THREAD

**Issue by BruceLi7** [3gstudent/pyKerbrute#4]
我在修改为ipv6的socket后会遇到后面data小于4的情况，然后就会进入死循环。
在去掉以后即可恢复正常。
所以想请问这个函数中循环是为了拼接data数据吗？
为什么ipv4会需要拼接数据呢，recv(8192)应该可以接收到所有data了吧？
![image](https://user-images.githubusercontent.com/104318205/164988022-b8b0236e-29f9-4137-aa41-575e32be9489.png)

**Comment by BruceLi7** [comment]
datalen的长度是1322
data的长度是1323
所以最后一个判断就失败了

**Comment by 3gstudent** [comment]
这段代码来自这里：
https://github.com/mubix/pykek/blob/afaaf68389c695f37bdca2a9c40fda1b3d86dab0/kek/krb5.py#L402

循环是为了拼接数据，考虑到编写其他功能的代码，所以这部分就没动。

当时没有考虑过ipv6的情况，等有空的时候会把ipv6的bug修复一下。

**Comment by BruceLi7** [comment]
感谢解惑。
